package entite;
// Generated 13-May-2020 11:29:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="CLIENT"
    ,schema="DEMO"
)
public class Client  implements java.io.Serializable {


     private int id;
     private UtilisateurWeb utilisateurWeb;
     private String nom;
     private String prenom;
     private String adresse;
     private String telephone;
     private String courriel;
     private String motPasse;
     private Set<Commande> commandes = new HashSet<Commande>(0);
     private Set<Lignecommande> lignecommandes = new HashSet<Lignecommande>(0);
     private Set<Paiement> paiements = new HashSet<Paiement>(0);

    public Client() {
    }

	
    public Client(int id, String nom, String prenom, String adresse, String telephone, String courriel, String motPasse) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.adresse = adresse;
        this.telephone = telephone;
        this.courriel = courriel;
        this.motPasse = motPasse;
    }
    public Client(int id, UtilisateurWeb utilisateurWeb, String nom, String prenom, String adresse, String telephone, String courriel, String motPasse, Set<Commande> commandes, Set<Lignecommande> lignecommandes, Set<Paiement> paiements) {
       this.id = id;
       this.utilisateurWeb = utilisateurWeb;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.telephone = telephone;
       this.courriel = courriel;
       this.motPasse = motPasse;
       this.commandes = commandes;
       this.lignecommandes = lignecommandes;
       this.paiements = paiements;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=5, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_UTILISATEUR_WEB")
    public UtilisateurWeb getUtilisateurWeb() {
        return this.utilisateurWeb;
    }
    
    public void setUtilisateurWeb(UtilisateurWeb utilisateurWeb) {
        this.utilisateurWeb = utilisateurWeb;
    }

    
    @Column(name="NOM", nullable=false, length=30)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRENOM", nullable=false, length=30)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="ADRESSE", nullable=false, length=100)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="TELEPHONE", nullable=false, length=30)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="COURRIEL", nullable=false, length=30)
    public String getCourriel() {
        return this.courriel;
    }
    
    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }

    
    @Column(name="MOT_PASSE", nullable=false, length=30)
    public String getMotPasse() {
        return this.motPasse;
    }
    
    public void setMotPasse(String motPasse) {
        this.motPasse = motPasse;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Commande> getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set<Commande> commandes) {
        this.commandes = commandes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Lignecommande> getLignecommandes() {
        return this.lignecommandes;
    }
    
    public void setLignecommandes(Set<Lignecommande> lignecommandes) {
        this.lignecommandes = lignecommandes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Paiement> getPaiements() {
        return this.paiements;
    }
    
    public void setPaiements(Set<Paiement> paiements) {
        this.paiements = paiements;
    }




}


