package entite;
// Generated 13-May-2020 11:29:20 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lignecommande generated by hbm2java
 */
@Entity
@Table(name="LIGNECOMMANDE"
    ,schema="DEMO"
)
public class Lignecommande  implements java.io.Serializable {


     private int id;
     private Produit produit;
     private Client client;
     private Commande commande;
     private int quantite;
     private int prix;

    public Lignecommande() {
    }

	
    public Lignecommande(int id, int quantite, int prix) {
        this.id = id;
        this.quantite = quantite;
        this.prix = prix;
    }
    public Lignecommande(int id, Produit produit, Client client, Commande commande, int quantite, int prix) {
       this.id = id;
       this.produit = produit;
       this.client = client;
       this.commande = commande;
       this.quantite = quantite;
       this.prix = prix;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=5, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PRODUIT")
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENT")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMMANDE")
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

    
    @Column(name="QUANTITE", nullable=false, precision=5, scale=0)
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }

    
    @Column(name="PRIX", nullable=false, precision=5, scale=0)
    public int getPrix() {
        return this.prix;
    }
    
    public void setPrix(int prix) {
        this.prix = prix;
    }




}


