package entite;
// Generated 13-May-2020 11:29:20 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaiementId generated by hbm2java
 */
@Embeddable
public class PaiementId  implements java.io.Serializable {


     private int idClient;
     private int idCommande;

    public PaiementId() {
    }

    public PaiementId(int idClient, int idCommande) {
       this.idClient = idClient;
       this.idCommande = idCommande;
    }
   


    @Column(name="ID_CLIENT", nullable=false, precision=5, scale=0)
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }


    @Column(name="ID_COMMANDE", nullable=false, precision=5, scale=0)
    public int getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(int idCommande) {
        this.idCommande = idCommande;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaiementId) ) return false;
		 PaiementId castOther = ( PaiementId ) other; 
         
		 return (this.getIdClient()==castOther.getIdClient())
 && (this.getIdCommande()==castOther.getIdCommande());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdClient();
         result = 37 * result + this.getIdCommande();
         return result;
   }   


}


