package entite;
// Generated 13-May-2020 11:29:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paiement generated by hbm2java
 */
@Entity
@Table(name="PAIEMENT"
    ,schema="DEMO"
)
public class Paiement  implements java.io.Serializable {


     private PaiementId id;
     private Client client;
     private Commande commande;
     private Date datePaie;
     private BigDecimal montant;
     private String typePaiement;

    public Paiement() {
    }

	
    public Paiement(PaiementId id, Client client, Commande commande, Date datePaie, BigDecimal montant) {
        this.id = id;
        this.client = client;
        this.commande = commande;
        this.datePaie = datePaie;
        this.montant = montant;
    }
    public Paiement(PaiementId id, Client client, Commande commande, Date datePaie, BigDecimal montant, String typePaiement) {
       this.id = id;
       this.client = client;
       this.commande = commande;
       this.datePaie = datePaie;
       this.montant = montant;
       this.typePaiement = typePaiement;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idClient", column=@Column(name="ID_CLIENT", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="idCommande", column=@Column(name="ID_COMMANDE", nullable=false, precision=5, scale=0) ) } )
    public PaiementId getId() {
        return this.id;
    }
    
    public void setId(PaiementId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENT", nullable=false, insertable=false, updatable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMMANDE", nullable=false, insertable=false, updatable=false)
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_PAIE", nullable=false, length=7)
    public Date getDatePaie() {
        return this.datePaie;
    }
    
    public void setDatePaie(Date datePaie) {
        this.datePaie = datePaie;
    }

    
    @Column(name="MONTANT", nullable=false, precision=8)
    public BigDecimal getMontant() {
        return this.montant;
    }
    
    public void setMontant(BigDecimal montant) {
        this.montant = montant;
    }

    
    @Column(name="TYPE_PAIEMENT", length=10)
    public String getTypePaiement() {
        return this.typePaiement;
    }
    
    public void setTypePaiement(String typePaiement) {
        this.typePaiement = typePaiement;
    }




}


