package entite;
// Generated 13-May-2020 11:29:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name="PRODUIT"
    ,schema="DEMO"
)
public class Produit  implements java.io.Serializable {


     private int id;
     private String nom;
     private String description;
     private String fabriquant;
     private BigDecimal prix;
     private String photo;
     private Set<Lignecommande> lignecommandes = new HashSet<Lignecommande>(0);

    public Produit() {
    }

	
    public Produit(int id, String nom, BigDecimal prix) {
        this.id = id;
        this.nom = nom;
        this.prix = prix;
    }

    public Produit(int id, String nom, String description, String fabriquant, BigDecimal prix, String photo) {
        this.id = id;
        this.nom = nom;
        this.description = description;
        this.fabriquant = fabriquant;
        this.prix = prix;
        this.photo = photo;
    }
    
    public Produit(int id, String nom, String description, String fabriquant, BigDecimal prix, String photo, Set<Lignecommande> lignecommandes) {
       this.id = id;
       this.nom = nom;
       this.description = description;
       this.fabriquant = fabriquant;
       this.prix = prix;
       this.photo = photo;
       this.lignecommandes = lignecommandes;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=5, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NOM", nullable=false, length=30)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="DESCRIPTION", length=80)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="FABRIQUANT", length=30)
    public String getFabriquant() {
        return this.fabriquant;
    }
    
    public void setFabriquant(String fabriquant) {
        this.fabriquant = fabriquant;
    }

    
    @Column(name="PRIX", nullable=false, precision=8)
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }

    
    @Column(name="PHOTO", length=30)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produit")
    public Set<Lignecommande> getLignecommandes() {
        return this.lignecommandes;
    }
    
    public void setLignecommandes(Set<Lignecommande> lignecommandes) {
        this.lignecommandes = lignecommandes;
    }




}


